### ISSUE TITLE
Daily status views

### ISSUE THREAD

**Issue by woongy** [fools-gold/crossroads#11]

**Comment by woongy** [comment]
라우트 설계를 어떻게 하면 좋을지 여기서 얘기해봅시다

**Comment by spilist** [comment]
라우트 설계, 즉 URL 디자인에서 무엇이, 왜 중요한가? 가장 먼저 생각나는 건 직관적이고 단순해야 한다는 것. 왜? 러닝 코스트가 낮아지니까. 약간 what u see is what u get 느낌...

아까는 statuses/daybefore/1 이런 식으로 얘기했었는데, 사용자가 새로운 라우트 daybefore를 학습할 필요 없이  statuses/today(또는 /2015-01-16)는 오늘 올라온 모든 스테이터스, statuses/yesterday (또는 /2015-01-15)는 어제 올라온 모든 스테이터스가 표시된다면 자연스럽게 /날짜 = 그날 올라온 모든 스테이터스 라고 생각할 것 같다. 즉 직관적이다.

**Comment by woongy** [comment]
여기서 '사용자 == 유저'를 말한 거라면 유저는 url이 어떻게 생겼는지 관심이 없엉... 각 페이지 기능은 gui로 전달하는 거고 대개 개발자가 아닌 사람들은 도메인 기억도 잘 못함.

그래서 개발자가 보기에 좋은가? 관점으로 봐야하는 게 더 맞고, 그런 의미에서 라우트를 이렇게 쓰는 건 reasonable 하다고 봄:

```ruby
resources :statuses do
  collection do
    get :today
    get :yesterday
    get '/:date', to: :on # 'statuses/2015-01-01'
  end
end
```

**Comment by woongy** [comment]
http://guides.rubyonrails.org/routing.html#segment-constraints 를 보면 `:date` 파라미터가 `yyyy-mm-dd` 포맷을 가질 때만 매치하도록 할 수도 있으니 참고 :)

**Comment by spilist** [comment]
나는 사용자==유저를 말한 거긴 했음. 음.. 유저는 url에 관심이 없구나. 하긴 나조차도 간단한 url은 다 외워서 쓰지만 결국은 클릭 클릭해서 들어가는군. 즉 개발자가 개발하기에 편한가 관점으로 봐야 하는거구나. 결론은 같지만 결론에 이르는 과정이 다르네.

**Comment by woongy** [comment]
개발하기 _편한가?_도 맞고, 뭔가 잘못 쓴 코드는 스멜이 난다고 하잖아? ㅋㅋ 라우트도 같은 관점에서 보면 됨

**Comment by spilist** [comment]
ㅇㅇ 결국 유지보수성에 관련이 있겠네. Clean code that works ㅋㅋ

**Comment by woongy** [comment]
꼭 저게 정답이 아니라, 예를 들면 이렇게 할 수도 있겠지?

```ruby
resources :statuses do
  collection do
    get :today
    get :yesterday
    get '/:year(/:month(/:date))', to: :on # 'statuses/2015', 'statuses/2015/01', 'statuses/2015/01/01'
  end
end
```

이렇게 하고 일별/월별/연별(?) 보기를 지원한다던가.. 결국 기능적인 관점에서도 생각해야함

**Comment by woongy** [comment]
지금은 `get '/:year/:month/:date'` 로 해서 일별 보기만 지원하게 구현하더라도 나중에 optional 하게 바꿔서 월별/연별 보기도 붙일 수 있으니까 `get ':date'` 보다 나은가? 라고 생각할 수도 있고, 아닐 수도 있고 ㅎ

지금은 큰 상관없지만, 실제 서비스 돌리는 거라면 SEO 적인 관점에서도 라우트 잘 짜는 게 도움이 되더라고

**Comment by spilist** [comment]
그렇군... 기능의 확장성도 생각해야 하고, 그리고 봇이 읽기 편한가도 생각해야 하는구나. 좋은 공부다

**Comment by woongy** [comment]
결정하고 구현 들어가면 될 듯? ㅎㅎ

**Comment by spilist** [comment]
장기적으로 볼 때는 
`resources :statuses do
  collection do
    get :today
    get :yesterday
    get '/:year/:month/:date', to: :on # 'statuses/2015', 'statuses/2015/01', 'statuses/2015/01/01'
  end
end`
쪽이 나은거같으니 이쪽으로 하겠음!

**Comment by woongy** [comment]
월별/연별 보기는 #16 에서 이어서 하기로
