### ISSUE TITLE
Likes on Status

### ISSUE THREAD

**Issue by woongy** [fools-gold/crossroads#12]
모델 설계를 어떻게 하면 좋을지부터 시작해봅시다

**Comment by CarsomyrJ** [comment]
모임에서 말한 것과 같이 RoR tutorial의 following-follower관계와 기본적으로 동일함. 방금 RoR tutorial chapter 12의 관련 내용을 읽어보니 relationship 이라는 별개의 모델을 정의해서 through를 통해 정의하고 있음. 

우리 프로젝트의 경우 user-user relationship이 아니고 status-user간 relationship이 정의되어야 할 듯. 이 경우 active_relationship은 어떤 status update를 몇 명의 유저들이 like했는가가 됨. Relationship모델은 다음과 같이 구현될듯.

| column | types |
|----| ------ |
| id | integer |
| like_user_id | integer |
| liked_status_id | integer |
| created_at | datetime |
| updated_at | datetime |

    class Relationship < ActiveRecord::Base
      belongs_to :like_user, class_name: "User"
      belongs_to :liked_status, class_name: "Status"
    end

    class Status < ActiveRecord::Base
      belongs_to :user
      has_and_belongs_to_many :hashtags, touch: true
      has_many :active_relationships, class_name: "Relationship", foreign_key: "like_user_id", dependent: :destroy

**Comment by woongy** [comment]
1. 튜토리얼의 팔로우 예제는 `Relationship` 이 모델 이름으로 적합하지. 이 경우에도 그럴까?
2. `Status#active_relationships` 는 뭘 가리키는 건지 모호하네 (이름도 그렇고 코드도 그렇고)
3. http://guides.rubyonrails.org/association_basics.html#the-has-many-through-association

**Comment by CarsomyrJ** [comment]
이름이 참 애매하긴 함... 몇 개 생각해 봤는데 어떤 게 좋을까

1. LikeRelation
    단순히 like기능을 위한 relation
2. StatusUser
    Status와 User간의 relation을 모델링 한 것을 의미
3. Action (or LikeAction)
    User가 status에 뭔가 하는 것을 action이라고 정의한다면...

지금와서 든 생각인데 나중에 unlike나 우리만의 다른 감정표현을 만들기 위해서는 Like라는 이름은 클래스명에서 빼는 것이 좋을 것 같기도 하다.

Status#active_relationships 는 사실 명시적으로 relationship들이랑 status랑 연관짓기 위해서 만든 녀석이고 실제  like한 유저에 해당하는 항목은 웅철이 링크해 준  through 기능을 활용하여 다음과 같이 나타낼 예정임. active_relationship대신 like_relation이란 이름을 임시로 사용하면 (1이 확정되어야 정확한 이름 결정할수 있을듯 ㅎㅎ)

```ruby
class Status < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :hashtags, touch: true
  has_many :like_relation, class_name: "Relationship",
                                                       foreign_key: "like_user_id", 
                                                       dependent: :destroy
  has_many :like_users, through: :like_relation, source: :liked_status
  ....
end
```

**Comment by woongy** [comment]
`Like` 어때?

**Comment by CarsomyrJ** [comment]
너무 복잡하게 생각하고 있었나 보다! 간단해서 좋네.  Like로 해도 like_users나 다른 것과 헷갈릴 염려 없으니 괜찮을꺼같다.

**Comment by woongy** [comment]
그럼 다시 모델 코드를 짜보면 어떻게 될까? (hint: `like_users` 라고 쓸 필요가 있을까?)

**Comment by CarsomyrJ** [comment]
이런식으로 짜면 될 것 같다. 어떠한가.

```ruby
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :status
end

class Status < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :hashtags, touch: true
  has_many :like_relation, class_name: "Like", foreign_key: "user_id", dependent: :destroy
  has_many :likes, through: :like_relation, source: :status
  ....
end
```

**Comment by woongy** [comment]
1. `status`를 좋아한 `user`들은 어떻게 가져올까
2. `user`가 좋아한 `status`들은 어떻게 가져올까

**Comment by woongy** [comment]
1. `status`를 좋아한 `user`들은 어떻게 가져올까
2. `user`가 좋아한 `status`들은 어떻게 가져올까
3. `Status#like_relation`은 뭘 가져오나
4. `Status#likes`는 뭘 가져오나

**Comment by CarsomyrJ** [comment]
1. Status#likes 로 like한 user list를 가져올 수 있다고 생각하고 모델링함. relation에서 관계를 만들면 likes에서 through를 통해 연관된 user list를 가져오는 구조
2. User객체에서도 Like와의 join을 통해 연관된 status들을 가져올 수 있을듯. 아래 코드와 같은 구조

   ```ruby
class User < ActiveRecord::Base
  ...
  has_many :statuses, dependent: :destroy
  has_many :liked_statues, through: :like
  ...
end
```
3. 해당 status와 연관된 like_relation의 개수
4. 해당 status를 like한 유저 list

말하다보니 만약 user list까지 필요 없고 좋아요 개수만 필요하다면 Status#likes는 굳이 필요하지 않겠네..

근데 과연 맞게 모델링한건가 싶어서 간단하게 짜 보는 중인데 like_relation create할때 버그가 있음. 다음 코드같이 짰는데 

```ruby
class Status < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :hashtags, touch: true
  has_many :like_relations, class_name: "Like",foreign_key: "user_id",
dependent: :destroy
  has_many :likes, through: :like_relations, source: :liked_status
  ... 
  def like(user)
    like_relations.create(user_id: user.id, status_id: self.id)
  end
  def unlike(user)
    like_relations.find_by(user_id: user.id, status_id: self.id).destroy
  end
end

Status.find(1).like(User.find(3)) 이라고 하면 3번 유저가 1번에 like 하도록 들어가야 하는데 자꾸 status id인 1번 유저 값이 user.id로 들어가고 있음... 좀 더 디버깅 해 보는중

**Comment by woongy** [comment]
1. 메소드 이름이 `likes` 라면 리턴값은 `Like` 객체들일거라고 짐작하겠지?
2. ㅇㅋ
3. "개수"라면 리턴값이 숫자라는 뜻??
4. 리턴값이 `User` 객체들이 아닐텐데... 그리고 1번 ㅊㄱ

이렇게 하면 어떨까:

```ruby
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :status
end

class User < ActiveRecord::Base
  has_many :likes
  has_many :liked_statuses, through: :likes, source: :status
end

class Status < ActiveRecord::Base
  has_many :likes
  has_many :likers, through: likes, source: :user
end
```

http://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#method-i-has_many-label-Options 를 보면 `class_name`과 `source`와 `foreign_key`가 언제 필요한지 나와있고, 이 경우에는 왜 `source`만 있으면 충분한지 알 수 있을 듯

1. 내가 위에 적은 모델 구성은 `dependent: :destroy`도 없고 한 유저가 한 스테이터스를 여러 번 라이크하지 못하게 막는 validation 도 없음. 그것들을 적절하게 추가해봅시다
2. `#like` 메소드는 어디에 있어야 할까: `status.like(user)` vs `user.like(status)`

**Comment by CarsomyrJ** [comment]
오오 이 경우에는 그냥 기본 클래스 이름인 user, status를 썼기 때문에 따로 foreign key를 사용하지 않아도 되는 것이군.

Like method는 아무래도 status에 있어야 하지 않을까. 사실 기능상 차이점은 없지만 실제 뷰 등의 형태로 구현할때 status를 확인하는 화면에서 like버튼을 누르면 해당 status 객체에 속한 Status#like가 불리는 것이 자연스러울꺼 같아.

말해준 사항들을 참고하여 구현을 시작하겠음.

**Comment by woongy** [comment]
ㄴㄴ 코드 읽는 관점에서 생각해봐. 루비 코드는 대개 자연어처럼 읽을 수 있는데, `like`의 주체는 유저이므로 `user.like(status)`가 더 자연스러움

**Comment by woongy** [comment]
컨트롤러나 라우트는 일단 생각하지말고, 여기까지 나온 것들을 고려해서 모델 코드만 짜보자 (마이그레이션도 포함)

**Comment by woongy** [comment]
라우트는 어떻게 할 지 여기서 먼저 정리해보고 컨트롤러 시작하자

**Comment by CarsomyrJ** [comment]
내가 like한 게시물들을 모아서 볼 수 있는 페이지가 하나 필요할 것 같다. users/like 라고 하면 될듯.

그 외에는 별달리 라우터나 컨트롤러는 필요없지 않을까? status/[id]/like, status/[id]/unlike 와 같이 like와 unlike 하는 액션 자체를 별도의 주소를 써서 처리하는건 동사를 가급적 쓰지 않고 http의 PUT, DELETE, GET등을 사용하는 restful에 별로 안맞는거같다.

**Comment by woongy** [comment]
1. 라이트한 거 모아보기는 하지 말자
2. "라우트가 필요없다"가 무슨 뜻인지 잘 모르겠는데, 예를 들어서 유저가 어떤 스테이터스에 '좋아요'를 눌렀을 때 그 요청이 서버에 어떻게 전달이 되어야하잖아? 그 요청을 어떤 라우트에서 받아서 어떤 컨트롤러가 처리할지 생각해보자는 뜻이었어. `Like` 모델 자체를 리소스라고 생당하면 restful 한 라우트를 정의할 수 있음

**Comment by CarsomyrJ** [comment]
Likes의 경우 개별 항목을 show하거나 likes만 따로 listup하지 않고, 생성 된 다음 별도로 update를 하지도 않으니까 create, destroy만 필요하겠다. RoR tutorial을 참고하면 다음과 같이 route를 정의할 수 있겠네. 

```ruby
Rails.application.routes.draw do
  #앞부분 생략
  resources :likes, only: [:create, :destroy]
end

**Comment by woongy** [comment]
http://guides.rubyonrails.org/routing.html#nested-resources 를 참고한다면 어떻게 될까

**Comment by CarsomyrJ** [comment]
아래와 같이 statuses 아래 likes가 nest되어야 할 것 같다. Users 아래가 아닌 이유는 유저 정보가 이미 session에 기록되어 있고 실제 사용자는 로그인 한 상태에서 특정 status를 향해 like action을 실행하게 될 것이므로...

```ruby
Rails.application.routes.draw do
  #앞부분 생략
  resources :statuses, except: [:show] do
    get :today, on: :collection
    resources :likes, only: [:create, :destroy]
  end
end

**Comment by woongy** [comment]
:+1: 이제 컨트롤러 구현해보자
