### ISSUE TITLE
Weekly/Yearly status view

### ISSUE THREAD

**Issue by woongy** [fools-gold/crossroads#16]
#11 에서 이어옴

**Comment by CarsomyrJ** [comment]
웅철 내가 다음과 같이 route를 바꾸고 StatusController#on 에서 마구 if문을 써 가면서 처리하려 하는데 괜찮을까.
```ruby
   resources :statuses, except: [:show] do
    collection do
      # 중략
      get "/:year(/:month(/:day))", action: :on
    end

**Comment by CarsomyrJ** [comment]
그리고 생각해보니까 monthly, yearly view에서는 status 수가 엄청 많을테니 daily처럼 한 화면에 다 그리는 제 좋지 않을 수 있을꺼같음. 상위 3개만 표시하고 나머지는 more...를 클릭할때마다 pagination처럼 10개씩 불러온다던가, 아님 3개만 표시하고 나머지는 해당 유저 클릭했을 때 /hoyoon/2014/02 같은 route를 새로 만들어서 거기서 표시 한다던가...

**Comment by woongy** [comment]
pagination 은 kaminari 라는 젬 써서 하면 되고 (`StatusesController#index` 참고) 이걸 ajax 로 가져다 붙일 수도 있겠지? 브랜치 파고 바로 ㄱㄱ 해봅시당

**Comment by woongy** [comment]
각 yearly/monthly/daily 페이지에서 previous/next year/month/day 로 가는 네비게이션도 추가해보자
