### ISSUE TITLE
Editing team profiles

### ISSUE THREAD

**Issue by woongy** [fools-gold/crossroads#20]
1. 현재 유저가 속한 팀의 이름, 소개글을 수정할 수 있게 하고
2. 권한을 가진 유저만 할 수 있도록 하자

**Comment by spilist** [comment]
3. Team 프로필 이미지를 올릴 수 있게 하면 어떨까?

**Comment by woongy** [comment]
그거는 젬 써야하니까 일단 나중에 ㅋㅋ

**Comment by spilist** [comment]
지금은 Team에 '소개글' 칼럼이 없으니까 이것부터 만들어야겠군? default는 비워두고.

**Comment by spilist** [comment]
'권한을 가진 유저만 할 수 있게 한다'를 위해서는 User 테이블에 어트리뷰트를 추가해야겠는데, team_authority 로 만들어서 값을 owner, read only, write 같은 걸로 해볼까 하는데 어떻게 생각함?
(owner는 나중에 '새 멤버를 팀에 추가하는' 요청이 들어왔을 때 허용하는 역할이라고 치고)

**Comment by spilist** [comment]
추가: 이런 경우에, 칼럼의 타입을 integer로 (owner=1, readonly=2, write=3) 하는 게 좋을까, string으로 (owner, read-only, write) 하는 게 좋을까, 또는 다른 더 좋은 방법이 있을까?
