### ISSUE TITLE
Attach photos to statuses

### ISSUE THREAD

**Issue by woongy** [fools-gold/crossroads#22]
https://github.com/thoughtbot/paperclip 을 써서 Status가 사진을 optionally 하나씩 가질 수 있게 하기. 작성 폼에서 첨부할 수 있게 하고 뷰에서 보여주는 처리도 해야함.

**Comment by spilist** [comment]
일단 MVP식으로는 끝난 것 같은데 이 이슈에서 어떤 걸 더 해볼까?

**Comment by woongy** [comment]
status 수정할 때, 이미 첨부한 사진을 삭제하고 싶으면 어떻게 해야할까

**Comment by woongy** [comment]
이거까지만 마무리하고 정리해서 PR 넣어주세요

**Comment by spilist** [comment]
사진을 삭제하거나 업데이트 가능하게 함. 그런데 사진을 넣었을 때, 바꿨을 때 ajax로 바로 사진을 보여주고 싶은데.. 아직 rails에서 ajax를 안써봐서 어떻게 할지 감이 안잡힌다 헬프요

**Comment by woongy** [comment]
(ajax 는 아니지만) #13 을 참고하면 되는데 보고 어려운 부분은 @CarsomyrJ 가 헬프해주자!
